# Generated by Django 3.0.7 on 2020-06-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200628_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='sub_date',
            field=models.DateTimeField(),
        ),
    ]
